name: 'Commit and Push Flights'
description: 'Commits and pushes IGC files, metadata, and state to GitHub'

inputs:
  airport_code:
    description: 'Airport code being processed'
    required: true
  workflow_type:
    description: 'Type of workflow (daily or manual)'
    required: true
  run_number:
    description: 'GitHub workflow run number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Commit and push flight data and state
      shell: bash
      run: |
        ./scripts/commit_and_push_flights.sh "${{ inputs.airport_code }}" "${{ inputs.workflow_type }}" "${{ inputs.run_number }}"
